"""
city_aliases.py — Auto-generated + curated city name alias map.
Generated from app/final.db with 15km proximity threshold.
"""

CITY_ALIASES: dict = {
    'abbarajupalem': 'sattenapalle',
    'acharapakkam': 'maduranthakam',
    'ahmedabad': 'maninagar taluka',
    'ainthapali': 'sambalpur',
    'akividu': 'kalidindi',
    'alampur mandal': 'kurnool',
    'alandur': 'pallavaram',
    'alipurduar - i': 'alipurduar',
    'alleppey': 'alappuzha',
    'allur': 'vidavalur',
    'aluru taluk': 'hassan',
    'aluva': 'ernakulam',
    'alwal mandal': 'secunderabad',
    'amadalavalasa': 'srikakulam',
    'amaravati': 'vijayawada',
    'ambajipeta': 'amalapuram',
    'aminpalli': 'maddikera (east)',
    'ammaianayakkanur': 'nilakkottai',
    'ampapuram': 'pedapadu',
    'anakapalle': 'kasimkota',
    'anantampalle': 'rajampet',
    'anaparti': 'medapadu',
    'angamaly': 'aluva',
    'anuppur': 'amlai',
    'apparaopalem': 'unguturu',
    'arakkonam': 'tiruttani',
    'arakonam': 'tiruttani',
    'araku valley': 'ananthagiri',
    'arasikere': 'arasikere taluku',
    'armoor mandal': 'armoor',
    'arulla': 'tadepalligudem',
    'asansol': 'asansol kulti township',
    'atchampet': 'krosuru',
    'atchutapuram': 'rambilli',
    'atlapadu': 'kovvur',
    'attili': '131',
    'avanigadda': 'repalle',
    'badami taluku': 'badami rd',
    'badampudi': 'tadepalligudem',
    'badangi': 'therlam',
    'badmal': 'jharsuguda',
    'bagalkote': 'bagalkot',
    'bagevadi': 'kolahara taluku',
    'bagnan': 'uluberia',
    'bagnan - ii': 'sahid matangini',
    'bahanaga': 'soro',
    'bahubalendrunigudem': 'penamaluru',
    'balabhadrapuram': 'medapadu',
    'balaghat': 'balagat tahsil',
    'balapur mandal': 'hyderabad',
    'balasore': 'baleshwar sadar',
    'baleshwar': 'baleshwar sadar',
    'balijipeta': 'veeraghattam',
    'ballari': 'bellary taluk',
    'bally': 'sankrail',
    'bangalore': 'bengaluru',
    'bangalore south': 'anekal',
    'bankura - i': 'bankura',
    'bantumilli': 'kalidindi',
    'bantwal': 'bantwal taluk',
    'bapulapadu': 'pedapadu',
    'barada': 'tumusingha',
    'barakar': 'asansol kulti township',
    'baranagar': 'kolkata',
    'baripada town': 'baripada',
    'basai': 'babina',
    'bastihalli': 'channarayapattana taluk',
    'beheraguda': 'seskhal',
    'belagam': 'parvathipuram',
    'belgaum': 'belagavi',
    'bellary': 'ballari',
    'betanati': 'baripada town',
    'bethamcherla': 'banaganapalle',
    'betnoti': 'mayurbhanj',
    'bhakarapeta': 'vontimitta',
    'bhalki taluku': 'bhalki',
    'bhamini': 'gunupur',
    'bhandari pokhari': 'korai',
    'bharuch': 'ankleshwar',
    'bhasma': 'jharsuguda',
    'bhatkal': 'bainduru',
    'bhatkal taluk': 'bhatkal',
    'bhavani': 'kumarapalayam',
    'bhimadole': 'unguturu',
    'bhiwandi': 'kalyan-dombivli',
    'bhogapuram': 'pusapatirega',
    'bhokar': 'nanded',
    'bhongiri mandal': 'bhongir',
    'bhubaneshwar': 'bhubaneswar',
    'bhubaneswar': 'nandankanan',
    'bibinagar': 'bhongiri mandal',
    'bijapur': 'vijayapura',
    'bikkavolu': 'medapadu',
    'bina etawa': 'khurai tahsil',
    'bina tahsil': 'khurai tahsil',
    'birkoor mandal': 'banswada mandal',
    'birur': 'kaduru taluk',
    'biswanathpur': 'banarpal',
    'bodinayakkanur': 'theni',
    'boinda': 'handapa',
    'bombay': 'mumbai',
    'bondamunda': 'rourkela',
    'bondapalli': 'vizianagaram',
    'brahmamgarimattam': 'sri avadhutha kasinayana',
    'brahmani tarang': 'rourkela',
    'brahmapur': 'berhampur',
    'brajanagar': 'korai',
    'brajarajnagar': 'jharsuguda',
    'bukkaraya samudram': 'garladinne',
    'burgampadu mandal': 'bhadrachalam',
    'burhar-dhanpuri': 'shahdol',
    'burja': 'palakonda',
    'burla': 'sambalpur',
    'calcutta': 'kolkata',
    'calicut': 'kozhikode',
    'chagallu': 'rajamahendravaram',
    'chalakudy': 'angamaly',
    'challapalle': 'movva',
    'chandarlapadu': 'krosuru',
    'chandori': 'nashik',
    'chandrapur': 'ballarshah',
    'chandrapura': 'bokaro',
    'chandwad taluka': 'manmad',
    'channapattana taluk': 'channapatna',
    'chavatapalem': 'naguluppala padu',
    'chebrolu': 'unguturu',
    'cheepurupalle': 'gurla',
    'chennai': 'chennai corporation',
    'cheranmahadevi': 'ambasamudram',
    'cherthala': 'alappuzha',
    'chettupodilam': 'rajam',
    'chhatia': 'badachana',
    'chikkaballapura taluk': 'sidlaghatta taluk',
    'chikkamagaluru taluku': 'beluru taluk',
    'chilamkuru': 'yerraguntla',
    'chinna gummuluru': 'yelamanchili',
    'chinnadugam': 'saravakota',
    'chinnamandem': 'rayachoti',
    'chittapura': 'chitapura taluku',
    'choudwar': 'gurudijhatia',
    'choutkur mandal': 'sangareddy mandal',
    'chowduwada': 'sabbavaram',
    'coast andhra': 'kalidindi',
    'cochin': 'ernakulam',
    'coimbatore': 'coimbatore south',
    'colliery': 'biswanathpur',
    'cuddalore township': 'cuddalore',
    'cumbum': 'bestawaripeta',
    'dachepalli': 'dachepalle',
    'dagadarthi': 'buchireddipalem',
    'dakkili': 'sydapuram',
    'damrun': 'chalisgaon',
    'dankuni': 'haora',
    'dantan': 'jaleswar',
    'dantan-i': 'jaleswar',
    'darbhanga': 'bahadurpur',
    'dasaripeta': 'tekkali',
    'dattirajeru': 'mentada',
    'davangere': 'davanagere',
    'degaon': 'basar mandal',
    'delhon pakhowal rd': 'ahmedgarh',
    'denkada': 'vizianagaram',
    'devakottai': 'ariyakudi road',
    'devanahalli taluku': 'sidlaghatta taluk',
    'devarapalle': 'rajavommangi',
    'devarkadra mandal': 'state highway 34',
    'devipatnam': 'rampachodavaram',
    'dhanbad': 'baghmara-cum-katras',
    'dharmasala': 'chhatia',
    'dhenkanal': 'dhenkanal sadar',
    'dist. dharwad': 'annigeri',
    'dist. kanniyakumari': 'nagercoil',
    'dolagobindapur': 'puri',
    'donakonda': 'darsi',
    'duburi': 'jakhapura',
    'duggirala': 'tenali',
    'dumbriguda': 'hukumpeta',
    'dundigal mandal': 'ramachandrapuram mandal',
    'dungripali': 'barapali',
    'durg': 'bhilai',
    'east godavari': 'kakinada',
    'elamanchilli': 'yelamanchili',
    'erragonda': 'chavitidibbalu',
    'etapaka': 'burgampadu mandal',
    'etapalem': 'visakhapatnam rural',
    'etcherla': 'srikakulam',
    'faizabad': 'ayodhya',
    'faridabad': 'ballabgarh',
    'fatehpur': 'varanasi',
    'fhulgaon': 'bhusaval',
    'gadag': 'gadag taluk',
    'gadwal mandal': 'gadwal',
    'gajapathinagaram': 'mentada',
    'ganapavaram': 'chebrolu',
    'gandipet mandal': 'ramachandrapuram mandal',
    'gangadhara nellore': 'chittoor',
    'gangarajupadu': 'kodur',
    'gangavaram': 'erragonda',
    'ganguvarisigadam': 'rajam',
    'ganjam': 'chhatrapur',
    'gankipadu': 'rajamahendravaram',
    'gannavaram': 'penamaluru',
    'gantyada': 'vizianagaram',
    'gara': 'narasannapeta',
    'garalamadugu': 'rajampet',
    'garbeta-i': 'chandrakona rd',
    'garladinne': 'anantapur',
    'garugubilli': 'parvathipuram',
    'gauribidanuru taluk': 'gauribidanuru',
    'gauriganj': 'amethi',
    'ghanpur': 'ghanpur (stn) mandal',
    'ghatal': 'sadar',
    'ghoti': 'igatpuri subdistrict',
    'ginigera': 'national highway 63',
    'gokak taluku': 'chikodi taluk',
    'golconda mandal': 'shamshabad mandal',
    'gollapalem': 'tadikonda',
    'gomoh': 'chandrapura',
    'gopavaram': 'badvel',
    'gorentla': 'maddirala mandal',
    'gotlam': 'vizianagaram',
    'govindpur': 'bamra',
    'gudivada': 'pamidimukkala',
    'gudlavalleru': 'pedana',
    'guduru': 'kodumur',
    'gulbarga': 'kalaburagi',
    'gullipādu': 'tuni',
    'guramaranahalli': 'channarayapattana taluk',
    'gurazala': 'dachepalli',
    'gurla': 'nellimarla',
    'gurramkonda': 'peddamandyam',
    'gurudijhatia': 'cuttack',
    'guwahati': 'dispur',
    'hajipur': 'patna',
    'hanamkonda mandal': 'warangal',
    'haora': 'sankrail',
    'haridwar': 'rishikesh',
    'harihara': 'davangere',
    'hastavaram': 'vontimitta',
    'hathras': 'devinagar',
    'haveli subdistrict': 'pimpri-chinchwad',
    'haveri': 'byadagi',
    'haveri taluku': 'haveri',
    'hirakud': 'sambalpur',
    'holalkere taluk': 'chikkajajur',
    'hospet': 'hosapete',
    'hosur': 'anekal',
    'howrah': 'haora',
    'howrah/kolkata': 'sankrail',
    'hubli': 'hubballi',
    'husnabad mandal': 'chigurumamidi mandal',
    'ibrahimpatnam mandal': 'abdullapurmet mandal',
    'igatpuri': 'ghoti',
    'ingur': 'perundurai',
    'inkollu': 'vetapalem',
    'jadcherla mandal': 'badepalli',
    'jagatpur': 'nirgundi',
    'jaggampeta': 'yeleswaram',
    'jagtial': 'jagtial mandal',
    'jaithari': 'anuppur',
    'jakkalacheruvu rs': 'gooty',
    'jaldega': 'hatibari',
    'jalumuru': 'narasannapeta',
    'jamadoba': 'jairampur more to baliapur',
    'jammikunta': 'shankarapatnam mandal',
    'jammu cantt': 'bari brahmana',
    'jangaon': 'aleru',
    'jangoan mandal': 'jangaon',
    'janjgir': 'akaltara',
    'jeelugu milli': 'jangareddigudem',
    'jenapur': 'jakhapura',
    'jind': 'district jind',
    'jiyyammavalasa': 'kurupam',
    'jogal': 'mayurbhanj',
    'jogapuram': 'tadpatri',
    'jolarpet': 'vaniyambadi',
    'jonk': 'gorphula',
    'k. gangavaram': 'ramachandrapuram',
    'kabisuryanagar': 'purusottampur',
    'kadayanallur': 'tenkasi',
    'kadgaon': 'bhusaval',
    'kadiri': 'gandlapenta',
    'kadur': 'kaduru taluk',
    'kaikalur': 'kalidindi',
    'kaikaluru': 'kalidindi',
    'kakinada rural': 'pithapuram',
    'kalambur': 'arani',
    'kalasapadu': 'sri avadhutha kasinayana',
    'kalikiri': 'pileru',
    'kallidaikurichchi': 'cheranmahadevi',
    'kallur': 'kurnool',
    'kamareddy mandal': 'kamareddy',
    'kamavarapukota': 'jangareddigudem',
    'kanchikacherla': 'nandigama',
    'kanchili': 'sompeta',
    'kandi mandal': 'sangareddy mandal',
    'kanhangad': 'bekal',
    'kankipadu': 'penamaluru',
    'kanyakumari': 'nagercoil',
    'karimnagar rural mandal': 'karimnagar',
    'karvetinagar': 'vedurukuppam',
    'karvir': 'hatkanangle',
    'karwar taluk': 'karwar',
    'kasara': 'igatpuri',
    'kasaragod district': 'kanhangad',
    'katpadi': 'vellore',
    'kattalaikudiyiruppu': 'tenkasi',
    'kavalagiriyanahalli': 'bangarapete',
    'kavali': 'gudluru',
    'kaviti': 'sompeta',
    'kayamkulam': 'karunagapally',
    'kazipet': 'warangal',
    'keesara mandal': 'secunderabad',
    'khaazipet mandal': 'warangal',
    'khadavli': 'kalyan-dombivli',
    'khadki': 'pune',
    'khagraghat': 'berhampore',
    'khamar nuagan': 'khuntuni',
    'khandagiri': 'bhubaneswar municipal corporation',
    'khannagar': 'baleshwar sadar',
    'kharagpur-ii': 'kharagpur',
    'kharsia tahsil': 'kharsia',
    'khordha sadar': 'tangi',
    'khurai': 'khurai tahsil',
    'khurda': 'tangi',
    'khurdha municipality boundary': 'tangi',
    'kilpennathur': 'kandachipuram',
    'kinnigoli': 'mulki taluk',
    'kirlampudi': 'yeleswaram',
    'kishorenagar': 'rairakhol',
    'kochi': 'ernakulam',
    'kodavalur': 'vidavalur',
    'kodumur': 'gonegandla',
    'koha': 'khurai tahsil',
    'kokrajhar': 'fakiragram',
    'kolar gold field taluk': 'bangarapete',
    'kolhapur': 'karvir',
    'koliana': 'baripada town',
    'kolluru': 'nagaram',
    'komali': 'tadpatri',
    'komarolu': 'giddalur',
    'kondagunta': 'jayampu',
    'kondamallapally mandal': 'devarakonda mandal',
    'kondapalli': 'amaravati',
    'konta tahsil': 'motu',
    'koppala': 'national highway 63',
    'koppala taluku': 'national highway 63',
    'koregaon': 'satara',
    'korisapadu': 'addanki',
    'korlam': 'polaki',
    'korukonda': 'rajanagaram',
    'kosigi': 'mantralayam',
    'kotabommali': 'santhabommali',
    'kotha patnam': 'tangutur',
    'kothagudem mandal': 'kothagudem',
    'kothapeta': 'k. gangavaram',
    'kothimahal tahsil': 'ujjain',
    'kothuru': 'seethampeta',
    'kotshila': 'jhalida',
    'kottarakkara': 'avaneeswaram pathanapuram rd',
    'kottayam': 'ettumanoor',
    'kovur': 'vidavalur',
    'kovvur': 'rajamahendravaram',
    'kowthalam': 'kosigi',
    'kozhikode': 'feroke',
    'kozhikode district': 'kozhikode',
    'krishna': 'sattenapalle',
    'krishna district': 'pamidimukkala',
    'krishnarajanagara taluk': 'krishnarajanagara',
    'krosuru': 'amaravathi',
    'kudachi': 'belgaum',
    'kuduru': 'maredumilli',
    'kukkaladoddi': 'kodur',
    'kumarapalayam': 'erode',
    'kumata taluk': 'uttara kannada',
    'kumbakonam': 'aduthurai',
    'kumbla': 'kasaragod',
    'kunavaram': 'velairpadu',
    'kundara': 'kottarakkara',
    'kuntikota': 'sompeta',
    'kurugodu taluk': 'sanduru taluk',
    'kuthalam': 'mayiladuthurai',
    'kutra': 'govindpur',
    'lahvit': 'igatpuri subdistrict',
    'laikera': 'jharsuguda',
    'lakkireddipalle': 'ramapuram',
    'lalapet': 'ammoor',
    'langaleswar': 'khalikote',
    'laveru': 'ganguvarisigadam',
    'lepakshi': 'hindupur',
    'londa': 'khanapura taluku',
    'lopudi': 'chodavaram',
    'lumding': 'diakkawn rd',
    'madakal': 'basheerabad mandal',
    'maddikera (east)': 'guntakal',
    'madhira mandal': 'madhira',
    'madhupada agraharam': 'mentada',
    'madras': 'chennai',
    'mahabubabad mandal': 'kesamudram mandal',
    'mahabubnagar': 'jadcherla mandal',
    'mahbubabad': 'mahabubabad mandal',
    'mahbubnagar': 'mahabubnagar',
    'maheshkhunt': 'khagaria',
    'makavarapalem': 'narsipatnam',
    'makkuva': 'salur',
    'malappuram': 'kuttippuram',
    'maldakal mandal': 'aiza mandal',
    'maligaon': 'guwahati',
    'malikipuram': 'sakhinetipalle',
    'maluru': 'kavalagiriyanahalli',
    'maluru taluk': 'maluru',
    'malvan taluka': 'kudal',
    'manakondur mandal': 'karimnagar rural mandal',
    'manapuram': 'mentada',
    'mancherial': 'ramagundam',
    'mancherial mandal': 'ramagundam',
    'mandapeta': 'ramachandrapuram',
    'mandya district': 'madduru taluk',
    'mangalagiri': 'vijayawada',
    'mangalore': 'mangaluru',
    'mantri palem': 'sabbavaram',
    'maradam': 'ramabhadrapuram',
    'marthandam': 'kalkulam',
    'matigara block': 'siliguri',
    'mavelikkara': 'kayamkulam',
    'mawal subdistrict': 'lonavala',
    'maynaguri': 'jalpaiguri',
    'medak mandal': 'medak',
    'medchal mandal': 'alwal mandal',
    'medinipur': 'kharagpur-ii',
    'medipally mandal': 'secunderabad',
    'meliaputti': 'tekkali',
    'merakamudidam': 'therlam',
    'metpalli mandal': 'korutla mandal',
    'midthur': 'gadivemula',
    'mihijam': 'jamtara',
    'miraj': 'jaysingpur',
    'miraj rd': 'jaysingpur',
    'mogallagunta': 'venkatagiri',
    'mogudampally mandal': 'dist. medak',
    'mokama': 'barauni',
    'molakalmuru taluku': 'rayadurg',
    'moodabidri taluk': 'karkala taluk',
    'mopidevi': 'avanigadda',
    'motu': 'chintur',
    'motunga': 'gudiacatenichak',
    'muddanuru': 'chilamkuru',
    'mudinepalle': 'krishna district',
    'mughalsarai': 'varanasi',
    'mundlamuru': 'narasapuram',
    'munirabad': 'hosapete',
    'muri': 'jhalida',
    'murudeshwara': 'bhatkal taluk',
    'murukkumpuzha': 'anchuthengu',
    'muthugoundenpudur': 'sulur',
    'muthukur': 'nellore',
    'mynagappally': 'kundara',
    'mysore': 'mysuru',
    'nabadwip': 'krishnanagar',
    'nagalapuram': 'satyavedu',
    'nagappattinam - gundlupet road(vandikara street)': 'kulithalai',
    'nagar_kurnool mandal': 'bijinapalle mandal',
    'nagaram': 'nizampatnam',
    'nagayalanka': 'koduru',
    'nagore': 'velankanni special grade town panchayath',
    'nagpur city': 'nagpur',
    'naguluppala padu': 'chinaganjam',
    'naini': 'prayagraj',
    'nainpur tahsil': 'nainpur',
    'nallajerla': 'tadepalligudem',
    'nambulipulikunta': 'gandlapenta',
    'nandaluru': 'vontimitta',
    'nandankanan': 'cuttack',
    'nandavaram': 'pedda kadubur',
    'nandgaon taluka': 'nandgaon',
    'nandigam': 'vajrapukothuru',
    'nandikotkur': 'alampur mandal',
    'nandivada': 'pedapadu',
    'nandre bk': 'erandol',
    'narasaraopeta': 'narasaraopet',
    'narayanapuram': 'kadapa',
    'narayangarh': 'dantan-i',
    'narayanpur': 'kumedpur',
    'narmadapuram': 'budhni',
    'narmetta mandal': 'mulug mandal',
    'narsampet mandal': 'duggondi mandal',
    'narsapur': 'sakhinetipalle',
    'national highway 7': 'tirunelveli',
    'navalagunda taluku': 'annigeri',
    'nayudupeta': 'naidupet',
    'near new bus stand shirdi sainagar': 'kopargaon',
    'needamangalam': 'mannargudi',
    'nelivada': 'vizianagaram',
    'nellimarla': 'pusapatirega',
    'neral': 'karjat',
    'neri': 'wardha',
    'nettana railway station': 'kadaba taluk',
    'new barrackpore': 'new town',
    'new delhi': 'delhi',
    'new komatipalli': 'ramabhadrapuram',
    'new town': 'baranagar',
    'nh 210': 'kallal',
    'nidadavole': 'kovvur',
    'nilagiri rd': 'shivani rd',
    'nileswaram': 'kasaragod district',
    'nimgaon': 'near new bus stand shirdi sainagar',
    'niphad': 'niphad taluka',
    'nirgundi': 'gurudijhatia',
    'nuzvid': 'agiripalle',
    'obaidullaganj': 'mandideep',
    'obulavaripalle': 'garalamadugu',
    'odakkadu': 'tiruppur',
    'odataraboi': 'delanga',
    'ojili': 'nayudupeta',
    'old gajuwaka': 'visakhapatnam',
    'omalur': 'salem',
    'oruguntapuram': 'pallipattu',
    'ottapidaram': 'kadambur',
    'paambukovil': 'kadayanallur',
    'pachora': 'nandre bk',
    'padappai': 'tambaram',
    'paderu': 'hukumpeta',
    'padmasaleela bazar': 'vijayawada',
    'pakala': 'pulicherla',
    'palacole': 'razole',
    'palakonda': 'veeraghattam',
    'palasa': 'vajrapukothuru',
    'palasamudram': 'pallipattu',
    'palayamkottai - kolathur - nagalapuram - aruppukottai rd': 'ottapidaram',
    'palghar': 'boisar',
    'pallavaram': 'chennai corporation',
    'pallikere': 'kanhangad',
    'pallipattu': 'nagari',
    'palvancha mandal': 'kothagudem mandal',
    'pamarru': 'pamidimukkala',
    'pamban': 'national highway 49',
    'pamidimukkala': 'movva',
    'panagallu': 'yerpedu',
    'pandhurna': 'narkhed',
    'paralakhemundi': 'pathapatnam',
    'paramakudi': 'paramagudi',
    'parappanangadi': 'kozhikode district',
    'parassala': 'marthandam',
    'paravada': 'pedagantyada',
    'paravur': 'kollam',
    'parvathagiri mandal': 'nekkonda mandal',
    'pasardi': 'bhadgaon',
    'patan tahsil': 'durg',
    'patas': 'daund',
    'pavoorchatram': 'tenkasi',
    'payakaraopeta': 'tuni',
    'payyoli': 'koyilandy',
    'pazhayangadi': 'kannur district',
    'peapally': 'jakkalacheruvu rs',
    'peda adisharla palli mandal': 'kondamallapally mandal',
    'peda araveedu': 'markapur',
    'peda bayalu': 'munchingi puttu',
    'pedacherlo palle': 'kanigiri',
    'pedakakani': 'tadikonda',
    'pedakurapadu': 'krosuru',
    'pedana': 'machilipatnam',
    'pedapadu': 'eluru',
    'pedavegi': 'unguturu',
    'pedda kadubur': 'mantralayam',
    'pedda vadlapudi': 'vijayawada',
    'peddapalli mandal': 'peddapalli',
    'peddapuram': 'kirlampudi',
    'penagalur': 'rajampet',
    'pendurthi': 'visakhapatnam rural',
    'penuganchiprolu': 'nandigama',
    'penugonda': 'penumantra',
    'penukonda': 'somandepalle',
    'penumantra': 'palakollu',
    'penumuru': 'vedurukuppam',
    'phillaur': 'ludhiana',
    'pigilam': 'venkatagiri',
    'pimpalas': 'niphad',
    'pimparkhed': 'naydongri',
    'pinaragivalasa': 'ramabhadrapuram',
    'pitampura': 'delhi',
    'pithapuram': 'peddapuram',
    'podanur': 'coimbatore south',
    'polaki': 'santhabommali',
    'police station rd': 'khagraghat',
    'ponduru': 'srikakulam',
    'ponnuru': 'ponnur',
    'poothura': 'murukkumpuzha',
    'porumamilla': 'sri avadhutha kasinayana',
    'prathipadu': 'rajamahendravaram',
    'pudukkottai taluk': 'pudukkottai',
    'pulicherla': 'pileru',
    'puligummi': 'parvathipuram',
    'pulla': 'unguturu',
    'pullirukkuvelur': 'sirkali',
    'punalur': 'avaneeswaram pathanapuram rd',
    'pune': 'pimpri-chinchwad',
    'purandhar': 'jejuri',
    'puri': 'chandanpur',
    'puthalapattu': 'penumuru',
    'quilon': 'kollam',
    'radhamohanpur': 'panskura',
    'radhapuram': 'nanguneri',
    'raghunathpally': 'jangoan mandal',
    'railway colony': 'cooch behar - ii',
    'rajagangapur': 'brahmani tarang',
    'rajagiri': 'kumbakonam',
    'rajahmundry': 'rajanagaram',
    'rajahmundry rural': 'rajanagaram',
    'rajam': 'therlam',
    'rajanagaram': 'rajamahendravaram',
    'rajavommangi': 'addateegala',
    'rajgangpur': 'rajagangapur',
    'ramabhadrapuram': 'seethanagaram',
    'ramakuppam': 'vaniyambadi',
    'ramanagara': 'channapattana taluk',
    'ramanagara taluk': 'ramanagara',
    'ramannapeta': 'narketpally mandal',
    'ramapuram': 'rayachoti',
    'ramayampet mandal': 'medak',
    'rambha': 'khalikote',
    'rameswaram': 'pamban',
    'ramnagar-i': 'digha',
    'ramnagar-ii': 'kanthi',
    'rampurhat - i': 'rampurhat',
    'ranastalam': 'laveru',
    'ranchi': 'bhusur',
    'rangampeta': 'medapadu',
    'rangapara': 'dhekiajuli (pt)',
    'rangareddy': 'medchal mandal',
    'rania': 'falna',
    'rapaka': 'santhakaviti',
    'raptadu': 'anantapur',
    'ravikamatham': 'lopudi',
    'ravulapalem': 'mandapeta',
    'rayagiri': 'bhongiri mandal',
    'rayalaseema region': 'vidapanakal',
    'rayanapad station': 'vijayawada',
    'razole': 'sakhinetipalle',
    'regadipalem': 'gangavaram',
    'regidi amadalavalasa': 'rajam',
    'rengali': 'ainthapali',
    'renigunta': 'tirupati',
    'repalle': 'nizampatnam',
    'revally mandal': 'gopalpet mandal',
    'rolla': 'agali',
    'rolugunta': 'narsipatnam',
    'rupsa': 'basta',
    'rustumpur': 'belagavi',
    'sabarmatitaluka': 'maninagar taluka',
    'sabbavaram': 'old gajuwaka',
    'sadashivnagar mandal': 'kamareddy mandal',
    'sagar tahsil': 'sagar',
    'sahanidiha': 'jenapur',
    'sahid matangini': 'kolaghat',
    'sakhigopal': 'puri',
    'sakti': 'naya baradwar',
    'salekasa': 'amgaon',
    'salem west': 'salem',
    'samalkha': 'gannaur',
    'samalkot': 'pithapuram',
    'samalkota': 'samalkot',
    'samalpatti': 'pochampalli',
    'sambaloor': 'chalakudy',
    'sambepalle': 'rayachoti',
    'samiyarpatti': 'nilakkottai',
    'sankagiri': 'tiruchengode',
    'sankarankoil': 'paambukovil',
    'sankarankovil': 'sankarankoil',
    'sankari': 'edappadi',
    'sankhavaram': 'gollaprolu',
    'sankrail': 'kolkata',
    'santhakaviti': 'srikakulam',
    'saravakota': 'kotabommali',
    'sarbahal': 'jharsuguda',
    'sarubujjili': 'saravakota',
    'sasan': 'sambalpur',
    'savda': 'fhulgaon',
    'secunderabad': 'hyderabad',
    'sedam': 'madakal',
    'sedam taluku': 'sedam',
    'seethamambapuram': 'komarada',
    'seethampeta': 'veeraghattam',
    'seetharamapuram': 'atmakur',
    'seetharampet': 'yerpedu',
    'seloo': 'helodi',
    'seoni': 'janjgir',
    'sh 19 junction mandya district': 'pandavapura taluk',
    'sh 44': 'bagalkote',
    'shadnagar': 'farooqnagar mandal',
    'shahapur': 'khadavli',
    'shahapur subdistrict': 'shahapur',
    'shamshabad': 'shamshabad mandal',
    'shamshabad mandal': 'gandipet mandal',
    'shilapur': 'pimpalas',
    'shimoga': 'shivamogga',
    'shirsoli p n': 'jalgaon',
    'sholavandan': 'vadipatti',
    'shoranur': 'pattambi',
    'sidhout': 'kadapa',
    'similia': 'jamujhadi',
    'similiguda': 'damonjodi',
    'singanamala': 'krishnagiri',
    'singarayakonda': 'tangutur',
    'singavaram': 'ravikamatham',
    'sivagiri': 'sankarankovil',
    'sivasagar': 'nazira',
    'sodam': 'pileru',
    'solapur': 'hotagi',
    'somanur': 'sulur',
    'somavaram': 'yelamanchili',
    'someshwar': 'manjeshwar',
    'sompeta': 'mandasa',
    'sonepur': 'patna',
    'srikakulam': 'narasannapeta',
    'srikalahasti': 'yerpedu',
    'sriperumbudur': 'padappai',
    'srirangam': 'tiruchirappalli',
    'srirangarajapuram': 'vedurukuppam',
    'state highway 19': 'rayadurg',
    'sultanabad mandal': 'peddapalli mandal',
    'sunabeda': 'similiguda',
    'sunam': 'sangrur',
    'supa taluk': 'dharbandora',
    'surat': 'chalthan',
    'surathkal': 'mulki taluk',
    'surendranagar': 'surendra nagar',
    'tada': 'sullurpeta',
    'tadali': 'chandrapur',
    'tadepalligudem': 'ganapavaram',
    'tadikonda': 'guntur',
    'tadipatri': 'tadpatri',
    'talbehat': 'basai',
    'talcher': 'colliery',
    'talegaon dabhade': 'haveli subdistrict',
    'tambaram': 'pallavaram',
    'tanduru': 'tandur mandal',
    'tangutur': 'ongole',
    'tanguturu': 'tangutur',
    'tanuku': 'penugonda',
    'tanur': 'parappanangadi',
    'taraori': 'ramnagar',
    'tarkhede bk': 'pasardi',
    'tarlupadu': 'peda araveedu',
    'tekkali': 'santhabommali',
    'telangana region': 'manuguru mandal',
    'thalayolaparambu': 'ettumanoor',
    'thane': 'bhiwandi',
    'thelkolois': 'sarbahal',
    'thenmala': 'aryankavu',
    'thirumalaiappapuram': 'pavoorchatram',
    'thirumangalam': 'vadipatti',
    'thiruvaiyaru': 'thanjavur',
    'thiruvalla': 'chengannur',
    'thiruvannamalai': 'tiruvannamalai',
    'thiruvarur': 'nannilam',
    'thiruverumbur': 'tiruchirappalli',
    'thiruvilliputtur state assembly constituency': 'rajapalayam',
    'thivim': 'pernem',
    'thondangi': 'sankhavaram',
    'thottambedu': 'yerpedu',
    'thrippunithura': 'kochi',
    'timarni': 'harda',
    'tiptur': 'tipaturu taluk',
    'tiruchchendur': 'arumuganeri',
    'tiruchengode': 'sankari',
    'tiruchirapalli fort station road': 'tiruchirappalli',
    'tirumangalam': 'thirumangalam',
    'tirunelveli': 'palayamkottai',
    'tirupattur': 'tirupathur',
    'tiruppurnorth': 'tiruppur',
    'tiruttani': 'nagari',
    'titlagarh': 'kesinga',
    'tittakudi': 'pennadam',
    'tohana': 'jakhal',
    'toturu': 'kanchili',
    'trichur': 'thrissur',
    'trivandrum': 'thiruvananthapuram',
    'tumkur': 'tumakuru',
    'tumusingha': 'dhenkanal sadar',
    'udhana': 'surat',
    'ulavapadu': 'singarayakonda',
    'ullala taluk': 'someshwar',
    'umaria': 'bandhogarh umaria tahsil',
    'undi': 'ganapavaram',
    'unjha': 'state highway 41',
    'uruli kanchan': 'purandhar',
    'uthukkottai': 'satyavedu',
    'uthukuli': 'tiruppurnorth',
    'vadamalapeta': 'renigunta',
    'vaddadi': 'singavaram',
    'vallakkunnu': 'sambaloor',
    'vallikkunnu': 'tanur',
    'vallioor': 'radhapuram',
    'vallur': 'narayanapuram',
    'vangara': 'veeraghattam',
    'vaniyambadi': 'tirupathur',
    'varadaiahpalem': 'tada',
    'vararamachandrapuram': 'velairpadu',
    'varkala': 'poothura',
    'vasind': 'shahapur subdistrict',
    'vatluru': 'pedapadu',
    'veerakeralamputhur': 'tenkasi',
    'veernapalli mandal': 'konaraopet mandal',
    'velankanni special grade town panchayath': 'nagapattinam',
    'velloor': 'thalayolaparambu',
    'vellore-632001': 'vellore',
    'vemagiri': 'rajanagaram',
    'vempalle': 'chakrayapet',
    'vemulapadu': 'komali',
    'vemulawada mandal': 'sircilla mandal',
    'venigandla': 'tadikonda',
    'venkatagirikota': 'baireddipalle',
    'vetapalem': 'chirala',
    'vijayapura': 'bijapur',
    'vijayawada': 'penamaluru',
    'vijayawada (rural)': 'vijayawada',
    'vikarabad mandal': 'vikarabad',
    'vikravandi': 'viluppuram',
    'villupuram': 'viluppuram',
    'vindhyachal': 'mirzapur',
    'vinukonda': 'gonuguntlavaripalem',
    'visakhapatnam rural': 'visakhapatnam',
    'vizag': 'visakhapatnam',
    'vizianagaram': 'nellimarla',
    'vuyyuru': 'pamidimukkala',
    'wadakkancherry': 'shoranur',
    'wallajah': 'lalapet',
    'waltair': 'visakhapatnam',
    'wanaparthy mandal': 'gopalpet mandal',
    'wargal mandal': 'gajwel mandal',
    'warora': 'majari',
    'warora taluka': 'warora',
    'yadagirigutta mandal': 'rayagiri',
    'yadgiri': 'yadagiri taluku',
    'yadiki': 'vemulapadu',
    'yelamanchili': 'rambilli',
    'yemmiganur': 'pedda kadubur',
    'yeola': 'kopargaon',
    'yercaud': 'salem west',
    'yerpedu': 'renigunta',
    'yerraguntla': 'proddatur',
    'zahirabad mandal': 'mogudampally mandal',
}
